version: 3

sources:
  - name: raw
    database: CASE
    schema: RAW
    tables:
      - name: amazon
        columns:
          - name: product_id
            tests:
              - not_null

          - name: review_id
            tests:
              - not_null
              - unique

          - name: user_id
            tests:
              - not_null